# site settings
title: Dulwich & Herne Hill Psychotherapy
subtitle: Dr. Paola Valerio
email: contact@dulwichpsychotherapy.com
description: Dr Paola Valerio is a jungian analyst offering psychotherapy, therapy, counselling and couples counselling in Dulwich, South London.
baseurl: '' # the subpath of your site, e.g. /blog
url: 'https://dulwichpsychotherapy.com' # the base hostname & protocol for your site
author: Paola Valerio
street_address: Herne Hill
city: London
state: ''
zip_code: SE24
country: United Kingdom
phone: 020 7733 8526
mobile: 0776 3311006

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url: null
facebook_url: null
github_url: null
gitlab_url: null
googleplus_url: null
instagram_url: null
linkedin_url: null
pinterest_url: null
slack_url: null
twitter_url: null

# build settings
markdown: kramdown

plugins:
  - jekyll-assets
  - jekyll-seo-tag
  - jekyll-sitemap

assets:
  source_maps: true # false on JEKYLL_ENV=production
  destination: "/assets"
  compression: false # true on JEKYLL_ENV=production
  gzip: false
  defaults:
    js: { integrity: false } # true on JEKYLL_ENV=production
    css: { integrity: false } # true on JEKYLL_ENV=production
    img: { integrity: false } # true on JEKYLL_ENV=production
  caching:
    path: ".jekyll-cache/assets"
    type: file # Possible values: memory, file
    enabled: true
  sources:
    - _assets/css
    - _assets/images
    - _assets/fonts
    - _assets/js
  caching:
    path: ".jekyll-cache/assets"
    type: file # Possible values: memory, file
    enabled: true
  sass:
    style: nested
    line_numbers: true
    sourcemap: file
  autoprefixer:
    browsers:
    - "last 2 versions"
    - "IE > 9"
  features:
    automatic_img_alt: true
  plugins:
    img:
      optim:
        optipng:
          level: 5
